version: "3"

services:
  phoenix:
    build: ./docker/images/elixir
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    environment:
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PGDATABASE: ${PGDATABASE}
      PGPORT: ${PGPORT}
      PGHOST: db
    depends_on:
      - db
    command:
      - "./entrypoint.sh"
    env_file:
      - "./.env"
  db:
    image: postgres:16.0
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./_pgdata:/var/lib/postgresql/data
    env_file:
      - "./.env"